#server.port=8181
#
## DataSource
#spring.datasource.url=jdbc:mariadb://localhost:3306/kms?autoReconnect=true
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root123

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

server:
  port: 8181
